package net.sr89.topology.worlds;

import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.VertexAttributes.Usage;
import com.badlogic.gdx.graphics.g3d.Environment;
import com.badlogic.gdx.graphics.g3d.Material;
import com.badlogic.gdx.graphics.g3d.Model;
import com.badlogic.gdx.graphics.g3d.ModelBatch;
import com.badlogic.gdx.graphics.g3d.ModelInstance;
import com.badlogic.gdx.graphics.g3d.attributes.BlendingAttribute;
import com.badlogic.gdx.graphics.g3d.attributes.ColorAttribute;
import com.badlogic.gdx.graphics.g3d.attributes.DepthTestAttribute;
import com.badlogic.gdx.graphics.g3d.attributes.IntAttribute;
import com.badlogic.gdx.graphics.g3d.utils.ModelBuilder;
import com.badlogic.gdx.math.Vector3;
import net.sr89.topology.HexColors;
import net.sr89.topology.math.Curve;
import net.sr89.topology.shapes.MarchingTetrahedra;
import net.sr89.topology.shapes.TubeMesh;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;

/**
 * The (hollow) surface of a double torus, a.k.a. the genus 2 surface.
 * <p>
 * Its fundamental group is generated by four loops, a pair for each hole: a loop {@code a} going around the hole,
 * and a loop {@code b} going around the "tube" of the surface (through the hole). It is
 * <pre>
 *     π₁ = ⟨ a₁, b₁, a₂, b₂ | a₁ b₁ a₁⁻¹ b₁⁻¹ a₂ b₂ a₂⁻¹ b₂⁻¹ ⟩
 * </pre>
 * One relation ties the four generators together (the product of the two commutators is trivial, because it
 * is the loop that cuts the surface into a disc), and the group is not abelian, unlike ℤ×ℤ for the torus.
 * <p>
 * The surface is the implicit surface {@code (x²(1 − x²) − y²)² + z² = r²}: a tube of radius r (thicker where
 * it crosses itself) following the figure-eight curve {@code y² = x²(1 − x²)} in the XY plane. The figure-eight's
 * two lobes are the two holes. For r < 1/4 the lobes stay open. We lay the surface flat on the XZ plane.
 * <p>
 * This world draws the translucent surface, the four generators, and one element of the fundamental group:
 * the path that goes once around hole 1 while winding once around the tube of the surface, then does the
 * same around hole 2 (roughly a₁ b₁ a₂ b₂, up to the orientation and basepoint conventions). A tracer moves along it.
 */
public class GenusTwoSurface implements World {
    /** Radius of the surface's "tube", in the unit coordinates the equation is written in. */
    static final float TUBE_RADIUS = 0.14f;
    /** The equation is written for a figure-eight about 2 units wide; this scales it to fit with the other worlds. */
    static final float SCALE = 2f;
    /** The loops are drawn slightly outside the surface so they aren't hidden inside it. */
    static final float LOOP_TUBE_RADIUS = TUBE_RADIUS * 1.04f;
    /** The center of each lobe, i.e. where each hole is. */
    private static final float LOBE_X = (float) Math.sqrt(0.5);
    /** Which level of g(x, y) = x²(1 − x²) − y² the "around the hole" loops follow: just inside the rim of the hole. */
    private static final float HOLE_LOOP_LEVEL = 0.5f * TUBE_RADIUS;

    private static final float GRID_CELL = 1f / 48f;
    private static final int LOOP_SAMPLES = 200;
    private static final int LOOP_SIDES = 8;
    private static final float LOOP_THICKNESS = 0.03f;
    private static final float PATH_RADIUS = TUBE_RADIUS * 1.08f; // slightly outside the generators, not to overlap them
    private static final float PATH_THICKNESS = 0.02f;
    private static final int PATH_SAMPLES = 800;
    private static final float TRACER_SECONDS_PER_LOOP = 25f;
    private static final float TRACER_DIAMETER = 0.16f;
    /** The path winds around the tube while going along this part of each lobe (as the angle ψ, see {@link #elementPath}). */
    private static final double WINDING_START = 0.35, WINDING_END = 1.25;

    private record Generator(Curve curve, Color color) {}

    private final List<Model> models = new ArrayList<>();
    private final ModelInstance surface;
    private final List<ModelInstance> loops = new ArrayList<>();
    private final ModelInstance path;
    private final Curve pathCurve = elementPath();
    private final ModelInstance tracer;

    private float progress = 0f; // in [0, 1)
    private final Vector3 tmp = new Vector3();

    public GenusTwoSurface() {
        surface = instance(createSurfaceModel());
        // The surface is built in the XY plane (with Z the thin direction), and Y is up in the world:
        // lay it flat, and scale it up.
        surface.transform.setToRotation(Vector3.X, -90f).scale(SCALE, SCALE, SCALE);

        final List<Generator> generators = List.of(
            new Generator(aroundHole(-1), Color.RED),
            new Generator(throughHole(-1), Color.CYAN),
            new Generator(aroundHole(+1), Color.ORANGE),
            new Generator(throughHole(+1), Color.MAGENTA));
        for (Generator generator : generators) {
            loops.add(instance(
                TubeMesh.build(generator.curve(), true, LOOP_SAMPLES, LOOP_SIDES, LOOP_THICKNESS, generator.color())));
        }
        path = instance(TubeMesh.build(
            pathCurve, true, PATH_SAMPLES, LOOP_SIDES, PATH_THICKNESS, HexColors.greenPastel()));

        tracer = instance(new ModelBuilder().createSphere(TRACER_DIAMETER, TRACER_DIAMETER, TRACER_DIAMETER, 12, 12,
            new Material(ColorAttribute.createDiffuse(Color.YELLOW)), Usage.Position | Usage.Normal));
        reposition(0f);
    }

    @Override
    public String getWorldTitle() {
        return "Genus 2 surface: <a1, b1, a2, b2 | [a1,b1][a2,b2]>";
    }

    @Override
    public void reposition(float deltaTime) {
        progress = (progress + deltaTime / TRACER_SECONDS_PER_LOOP) % 1f;
        pathCurve.pointAt(progress, tmp);
        tracer.transform.setToTranslation(tmp);
    }

    @Override
    public void render(ModelBatch modelBatch, Environment environment) {
        // ModelBatch draws blended renderables (the surface) after opaque ones, back to front.
        for (ModelInstance loop : loops) {
            modelBatch.render(loop, environment);
        }
        modelBatch.render(path, environment);
        modelBatch.render(tracer, environment);
        modelBatch.render(surface, environment);
    }

    @Override
    public void dispose() {
        models.forEach(Model::dispose);
    }

    /** Creates an instance of the model, and takes ownership of the model to dispose of it later. */
    private ModelInstance instance(Model model) {
        models.add(model);
        return new ModelInstance(model);
    }

    /** The x²(1 − x²) − y² part of the equation: positive inside the two lobes, negative outside the figure-eight. */
    static float g(float x, float y) {
        return x * x * (1 - x * x) - y * y;
    }

    private static Model createSurfaceModel() {
        final Material material = new Material(
            ColorAttribute.createDiffuse(HexColors.greenPastel()),
            new BlendingAttribute(GL20.GL_SRC_ALPHA, GL20.GL_ONE_MINUS_SRC_ALPHA, 0.35f),
            IntAttribute.createCullFace(GL20.GL_NONE), // hollow: visible from inside too
            // Test against the depth buffer but don't write to it, so we can see through to the far side.
            new DepthTestAttribute(GL20.GL_LEQUAL, false)
        );
        return createSurfaceModel(material, null);
    }

    /**
     * The surface, in the unit coordinates of its equation.
     *
     * @param keep only keeps the triangles with their center accepted by this filter (in those coordinates), to get
     *             a part of the surface; null keeps the whole surface
     */
    static Model createSurfaceModel(Material material, Predicate<Vector3> keep) {
        return MarchingTetrahedra.build(
            GenusTwoSurface::field, new Vector3(-halfWidth(), -halfHeight(), -halfDepth()),
            new Vector3(halfWidth(), halfHeight(), halfDepth()), GRID_CELL, material, keep);
    }

    /** The raw mesh of the surface, in the unit coordinates of its equation, with cells of the given size. */
    static MarchingTetrahedra.Triangulation createTriangulation(float cell) {
        return MarchingTetrahedra.triangulate(
            GenusTwoSurface::field, new Vector3(-halfWidth(), -halfHeight(), -halfDepth()),
            new Vector3(halfWidth(), halfHeight(), halfDepth()), cell);
    }

    /** The function that is zero on the surface, negative inside it and positive outside. */
    static float field(float x, float y, float z) {
        final float g = g(x, y);
        return g * g + z * z - TUBE_RADIUS * TUBE_RADIUS;
    }

    // The surface reaches x = ±(1 + r/2) and y = ±√(1/4 + r), and z = ±r. Leave a bit of room.
    private static final float BOUNDS_MARGIN = 0.04f;

    private static float halfWidth() {
        return 1f + TUBE_RADIUS / 2 + BOUNDS_MARGIN;
    }

    private static float halfHeight() {
        return (float) Math.sqrt(0.25 + TUBE_RADIUS) + BOUNDS_MARGIN;
    }

    private static float halfDepth() {
        return TUBE_RADIUS + BOUNDS_MARGIN;
    }

    /**
     * The loop "a" going around the hole of one lobe, along the top of the surface just inside the hole's rim.
     * That is the closed curve g(x, y) = level, at the height z where the surface is.
     *
     * @param side -1 for the left lobe, +1 for the right lobe
     */
    static Curve aroundHole(int side) {
        // g(x, 0) = level has two positive solutions for x² (the oval's left and right ends)
        final double root = Math.sqrt(1 - 4 * HOLE_LOOP_LEVEL);
        final double left = Math.sqrt((1 - root) / 2), right = Math.sqrt((1 + root) / 2);
        final double middle = (left + right) / 2, radius = (right - left) / 2;
        final double z = Math.sqrt(LOOP_TUBE_RADIUS * LOOP_TUBE_RADIUS - HOLE_LOOP_LEVEL * HOLE_LOOP_LEVEL);

        return (t, out) -> {
            final double angle = 2 * Math.PI * t;
            final double x = middle + radius * Math.cos(angle);
            // y = ±√(g - level). The sign follows the angle, which makes the curve smooth where it turns around.
            final double y = Math.sqrt(Math.max(g((float) x, 0f) - HOLE_LOOP_LEVEL, 0)) * Math.signum(Math.sin(angle));
            toWorld(side * (float) x, (float) y, (float) z, out);
        };
    }

    /**
     * The loop "b" going once around the surface's tube, at the front of one lobe. It lies in the plane x = lobe center.
     *
     * @param side -1 for the left lobe, +1 for the right lobe
     */
    static Curve throughHole(int side) {
        final double centerG = g(LOBE_X, 0f);
        return (t, out) -> {
            final double angle = 2 * Math.PI * t;
            // a circle of radius r in the (g, z) plane: g = r cos(angle), z = r sin(angle), with y < 0, which is the
            // front of the surface when it is seen from where the camera starts (see toWorld)
            final double y = -Math.sqrt(centerG - LOOP_TUBE_RADIUS * Math.cos(angle));
            final double z = LOOP_TUBE_RADIUS * Math.sin(angle);
            toWorld(side * LOBE_X, (float) y, (float) z, out);
        };
    }

    /**
     * The element of the fundamental group we trace: a closed curve starting and ending at the top of the surface
     * where the two lobes meet, going around the first lobe and then the second.
     * <p>
     * The crest of lobe 1 is the curve g(x, y) = 0 at the top of the surface, x = sin ψ, y = sin ψ cos ψ (ψ from 0 to π),
     * and the crest of lobe 2 is its mirror image. Following only the crest would give a loop around the hole.
     * To also wind around the tube, as we go the point is moved off the crest, around the tube's cross-section:
     * the cross-section of the surface is the circle g = R cos φ, z = R sin φ, and φ goes through one full turn
     * smoothly as ψ goes through {@link #WINDING_START} to {@link #WINDING_END}. For a given φ we find where
     * g(x, y) = R cos φ by moving off the crest, perpendicular to it.
     */
    private static Curve elementPath() {
        return (t, out) -> {
            final double wrapped = t - Math.floor(t); // the tangent is estimated slightly outside [0, 1]
            final int lobe = wrapped < 0.5 ? 0 : 1;
            final double psi = Math.PI * (2 * wrapped - lobe);

            // the crest, its direction, and the unit vector perpendicular to it
            final double crestX = Math.sin(psi), crestY = Math.sin(psi) * Math.cos(psi);
            final double directionX = Math.cos(psi), directionY = Math.cos(2 * psi);
            final double length = Math.hypot(directionX, directionY);
            final double normalX = -directionY / length, normalY = directionX / length;

            final double progress = Math.min(Math.max((psi - WINDING_START) / (WINDING_END - WINDING_START), 0), 1);
            final double phi = Math.PI / 2 + 2 * Math.PI * progress * progress * (3 - 2 * progress);
            final double wantedG = PATH_RADIUS * Math.cos(phi);

            // Newton's method along the normal, starting at the crest, to find where g reaches the wanted value
            double offset = 0;
            for (int i = 0; i < 8; i++) {
                final double x = crestX + offset * normalX, y = crestY + offset * normalY;
                final double slope = (2 * x - 4 * x * x * x) * normalX - 2 * y * normalY;
                if (Math.abs(slope) < 1e-4) {
                    break;
                }
                offset -= (g((float) x, (float) y) - wantedG) / slope;
            }
            final double x = crestX + offset * normalX, y = crestY + offset * normalY;

            final int side = lobe == 0 ? +1 : -1;
            toWorld(side * (float) x, (float) y, (float) (PATH_RADIUS * Math.sin(phi)), out);
        };
    }

    /** Where a point of the surface (in the unit coordinates of its equation) ends up in the world. */
    static void toWorld(float x, float y, float z, Vector3 out) {
        out.set(SCALE * x, SCALE * z, -SCALE * y);
    }
}
