package net.sr89.topology.worlds;

import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.g3d.Environment;
import com.badlogic.gdx.graphics.g3d.Model;
import com.badlogic.gdx.graphics.g3d.ModelBatch;
import com.badlogic.gdx.graphics.g3d.ModelInstance;
import com.badlogic.gdx.math.Vector3;
import net.sr89.topology.HexColors;
import net.sr89.topology.math.Curve;
import net.sr89.topology.shapes.Flag;
import net.sr89.topology.shapes.ParametricSurface;
import net.sr89.topology.shapes.TubeMesh;

import java.util.ArrayList;
import java.util.List;

/**
 * The Möbius band: a strip whose two ends are glued after a half twist.
 * <p>
 * It deformation retracts onto its core circle (red), so its fundamental group is ℤ, generated by the loop a that goes
 * once around the core. Its boundary (magenta) is a single circle, and it goes twice around the band before closing up:
 * in the fundamental group the boundary is a². This is why the inclusion of the boundary into the band
 * is multiplication by 2 on ℤ.
 * <p>
 * The band is non-orientable. A flag moving around the core (a ball on the surface and a small ball over it, on one side)
 * is on the other side of the band after one lap, and back on its original side after two.
 */
public class MobiusBand implements World {
    private static final float RADIUS = 1.6f;
    private static final float HALF_WIDTH = 0.6f;
    private static final int LOOP_SAMPLES = 300;
    private static final float TRACER_SECONDS_PER_LAP = 8f;
    private static final float TUBE_THICKNESS = 0.035f;

    private final List<Model> models = new ArrayList<>();
    private final ModelInstance surface;
    private final ModelInstance core;
    private final ModelInstance boundary;
    private final Flag flag = new Flag(Color.YELLOW, Color.WHITE);

    private float laps = 0f; // in [0, 2)
    private final Vector3 position = new Vector3();
    private final Vector3 normal = new Vector3();

    public MobiusBand() {
        surface = instance(ParametricSurface.build(MobiusBand::point, 160, 16, false,
            ParametricSurface.translucentMaterial(HexColors.greenPastel(), 0.5f)));

        // the core goes around once, the boundary twice
        final Curve coreCurve = (t, out) -> pointAt(2 * Math.PI * t, 0, out);
        final Curve boundaryCurve = (t, out) -> pointAt(4 * Math.PI * t, HALF_WIDTH, out);
        core = instance(TubeMesh.build(coreCurve, true, LOOP_SAMPLES, 8, TUBE_THICKNESS, Color.RED));
        boundary = instance(TubeMesh.build(boundaryCurve, true, 2 * LOOP_SAMPLES, 8, TUBE_THICKNESS, Color.MAGENTA));
        reposition(0f);
    }

    @Override
    public String getWorldTitle() {
        return "Mobius band: pi1 = Z, the boundary is a^2";
    }

    @Override
    public void reposition(float deltaTime) {
        laps = (laps + deltaTime / TRACER_SECONDS_PER_LAP) % 2f;
        final float u = laps % 1f;
        point(u, 0.5f, position);
        ParametricSurface.normalAt(MobiusBand::point, u, 0.5f, normal);
        // After a full lap around the core, the normal vector ends up as its opposite (non-orientability). To make the
        // flag move continuously, we flip it again for each full lap, so it is on the other side in the second lap.
        if (laps >= 1f) {
            normal.scl(-1f);
        }
        flag.place(position, normal);
    }

    @Override
    public void render(ModelBatch modelBatch, Environment environment) {
        modelBatch.render(core, environment);
        modelBatch.render(boundary, environment);
        flag.render(modelBatch, environment);
        modelBatch.render(surface, environment);
    }

    @Override
    public void dispose() {
        models.forEach(Model::dispose);
        flag.dispose();
    }

    /** The band as a surface: u goes around the core (from 0 to 1), v goes across the width of the band. */
    private static void point(float u, float v, Vector3 out) {
        pointAt(2 * Math.PI * u, HALF_WIDTH * (2 * v - 1), out);
    }

    /**
     * @param angle angle around the core, in radians. The band makes a half twist for each full turn, so
     *              angle + 2π is the same point of the core, but the other side of the band.
     * @param offset signed distance from the core across the band
     */
    private static void pointAt(double angle, double offset, Vector3 out) {
        final double ring = RADIUS + offset * Math.cos(angle / 2);
        // Y is up in the world
        out.set((float) (ring * Math.cos(angle)), (float) (offset * Math.sin(angle / 2)), (float) (ring * Math.sin(angle)));
    }

    private ModelInstance instance(Model model) {
        models.add(model);
        return new ModelInstance(model);
    }
}
