package net.sr89.topology.worlds;

import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.VertexAttributes.Usage;
import com.badlogic.gdx.graphics.g3d.Environment;
import com.badlogic.gdx.graphics.g3d.Material;
import com.badlogic.gdx.graphics.g3d.Model;
import com.badlogic.gdx.graphics.g3d.ModelBatch;
import com.badlogic.gdx.graphics.g3d.ModelInstance;
import com.badlogic.gdx.graphics.g3d.attributes.ColorAttribute;
import com.badlogic.gdx.graphics.g3d.utils.ModelBuilder;
import com.badlogic.gdx.math.Interpolation;
import com.badlogic.gdx.math.Vector3;
import net.sr89.topology.math.Curve;
import net.sr89.topology.shapes.ParametricSurface;
import net.sr89.topology.shapes.TubeMesh;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;

/**
 * The idea of the Seifert-van Kampen theorem (and of Mayer-Vietoris, its cousin for homology): compute the topology of a
 * space X from two open pieces A and B that cover it, and from their intersection.
 * <p>
 * Here X is the genus 2 surface, A is its left half (blue) and B its right half (orange). Each is a torus with a hole
 * (so its fundamental group is free on two generators: a₁, b₁ for A, a₂, b₂ for B), and they overlap in the neck
 * between the two holes, which is a cylinder: A ∩ B has the fundamental group ℤ, generated by the loop e around the neck (yellow).
 * <p>
 * The theorem says that π₁(X) is built by taking all the generators of A and of B together, and then identifying the images
 * of the generator of π₁(A ∩ B) in π₁(A) and in π₁(B). The loop e goes around the hole of A, so in A it is the commutator
 * a₁ b₁ a₁⁻¹ b₁⁻¹; in B it is the same loop, going the other way around, [a₂, b₂]⁻¹. So the relation is
 * [a₁, b₁] = [a₂, b₂]⁻¹, i.e.
 * <pre>
 *     π₁(X) = ⟨ a₁, b₁, a₂, b₂ | [a₁, b₁] [a₂, b₂] ⟩
 * </pre>
 * The two pieces slowly move apart to show them, with the loops that live in each (and the loop e, which lives in both).
 * Tracers go around e in A and in B at the same time.
 */
public class VanKampenGenusTwo implements World {
    /** A is the part of the surface to the left of this, and B the part to the right of minus this (in unit coordinates, so they overlap). */
    private static final float OVERLAP = 0.12f;
    private static final float SEPARATION = 1.6f;
    private static final float SURFACE_OPACITY = 0.4f;
    private static final float LOOP_RADIUS = 0.03f;
    private static final int LOOP_SAMPLES = 200;
    private static final float TRACER_SECONDS = 12f;

    // seconds
    private static final float TOGETHER = 3f, MOVING = 4f, APART = 5f;
    private static final float CYCLE = TOGETHER + MOVING + APART + MOVING;

    private static final Color COLOR_A = new Color(0.40f, 0.60f, 1f, 1f);
    private static final Color COLOR_B = new Color(1f, 0.65f, 0.30f, 1f);

    private final List<Model> models = new ArrayList<>();
    private final List<ModelInstance> inA = new ArrayList<>();
    private final List<ModelInstance> inB = new ArrayList<>();
    private final ModelInstance neckLoopInA;
    private final ModelInstance neckLoopInB;
    private final ModelInstance tracerInA;
    private final ModelInstance tracerInB;
    private final Curve neckLoop = VanKampenGenusTwo::neckLoop;

    private float time = 0f;
    private float apart = 0f; // 0: together, 1: apart
    private float progress = 0f; // in [0, 1)
    private final Vector3 tmp = new Vector3();

    public VanKampenGenusTwo() {
        final Predicate<Vector3> leftHalf = center -> center.x < OVERLAP;
        final Predicate<Vector3> rightHalf = center -> center.x > -OVERLAP;
        inA.add(instance(GenusTwoSurface.createSurfaceModel(
            ParametricSurface.translucentMaterial(COLOR_A, SURFACE_OPACITY), leftHalf)));
        inB.add(instance(GenusTwoSurface.createSurfaceModel(
            ParametricSurface.translucentMaterial(COLOR_B, SURFACE_OPACITY), rightHalf)));
        // the surface is built in the XY plane, with Z the thin direction, and Y is up in the world: lay it flat
        for (ModelInstance surface : List.of(inA.get(0), inB.get(0))) {
            surface.transform.setToRotation(Vector3.X, -90f).scale(
                GenusTwoSurface.SCALE, GenusTwoSurface.SCALE, GenusTwoSurface.SCALE);
        }

        // the loops of A and of B
        inA.add(loop(GenusTwoSurface.aroundHole(-1), Color.RED));
        inA.add(loop(GenusTwoSurface.throughHole(-1), Color.WHITE));
        inB.add(loop(GenusTwoSurface.aroundHole(+1), Color.GREEN));
        inB.add(loop(GenusTwoSurface.throughHole(+1), Color.MAGENTA));

        // the loop in the intersection, as part of A and as part of B
        neckLoopInA = loop(neckLoop, Color.YELLOW);
        neckLoopInB = loop(neckLoop, Color.YELLOW);
        inA.add(neckLoopInA);
        inB.add(neckLoopInB);

        final Model tracer = model(new ModelBuilder().createSphere(0.2f, 0.2f, 0.2f, 12, 12,
            new Material(ColorAttribute.createDiffuse(Color.YELLOW)), Usage.Position | Usage.Normal));
        tracerInA = new ModelInstance(tracer);
        tracerInB = new ModelInstance(tracer);
        reposition(0f);
    }

    @Override
    public String getWorldTitle() {
        return apart < 0.5f
            ? "Van Kampen: A (blue) and B (orange) cover the surface, and overlap in the neck"
            : "Van Kampen: the loop e is [a1,b1] in A and [a2,b2]^-1 in B";
    }

    @Override
    public void reposition(float deltaTime) {
        time = (time + deltaTime) % CYCLE;
        progress = (progress + deltaTime / TRACER_SECONDS) % 1f;

        final float amount;
        if (time < TOGETHER) {
            amount = 0f;
        } else if (time < TOGETHER + MOVING) {
            amount = (time - TOGETHER) / MOVING;
        } else if (time < TOGETHER + MOVING + APART) {
            amount = 1f;
        } else {
            amount = 1f - (time - TOGETHER - MOVING - APART) / MOVING;
        }
        apart = Interpolation.smooth.apply(amount);

        // A goes to the left, and B goes to the right
        for (ModelInstance instance : inA) {
            shift(instance, -apart * SEPARATION);
        }
        for (ModelInstance instance : inB) {
            shift(instance, apart * SEPARATION);
        }

        neckLoop.pointAt(progress, tmp);
        tracerInA.transform.setToTranslation(tmp.x - apart * SEPARATION, tmp.y, tmp.z);
        tracerInB.transform.setToTranslation(tmp.x + apart * SEPARATION, tmp.y, tmp.z);
    }

    @Override
    public void render(ModelBatch modelBatch, Environment environment) {
        // ModelBatch draws blended renderables (the surfaces) after opaque ones, back to front.
        for (ModelInstance instance : inA) {
            modelBatch.render(instance, environment);
        }
        for (ModelInstance instance : inB) {
            modelBatch.render(instance, environment);
        }
        modelBatch.render(tracerInA, environment);
        modelBatch.render(tracerInB, environment);
    }

    @Override
    public void dispose() {
        models.forEach(Model::dispose);
    }

    /**
     * The loop around the neck, in the plane where x = 0, on the (inflated) surface y⁴ + z² = r². It goes around once
     * as θ goes from 0 to 2π, with y = √r sin θ, so z = ±√(r² − y⁴) (the sign being that of cos θ) changes sign smoothly.
     */
    private static void neckLoop(float t, Vector3 out) {
        final double theta = 2 * Math.PI * t;
        final double r = GenusTwoSurface.LOOP_TUBE_RADIUS;
        final double y = Math.sqrt(r) * Math.sin(theta);
        final double z = Math.signum(Math.cos(theta)) * Math.sqrt(Math.max(r * r - y * y * y * y, 0));
        GenusTwoSurface.toWorld(0f, (float) y, (float) z, out);
    }

    /** Moves an instance sideways, without changing the rest of its transform. */
    private static void shift(ModelInstance instance, float x) {
        final Vector3 position = instance.transform.getTranslation(new Vector3());
        instance.transform.setTranslation(x, position.y, position.z);
    }

    private ModelInstance loop(Curve curve, Color color) {
        return instance(TubeMesh.build(curve, true, LOOP_SAMPLES, 8, LOOP_RADIUS, color));
    }

    /** Takes ownership of the model to dispose of it later. */
    private Model model(Model model) {
        models.add(model);
        return model;
    }

    private ModelInstance instance(Model model) {
        return new ModelInstance(model(model));
    }
}
