allprojects {
  apply plugin: 'eclipse'
  apply plugin: 'idea'

  // This allows you to "Build and run using IntelliJ IDEA", an option in IDEA's Settings.
  idea {
    module {
      outputDir file('build/classes/java/main')
      testOutputDir file('build/classes/java/test')
    }
  }
}

configure(subprojects) {
  apply plugin: 'java-library'
  sourceCompatibility = 17
  compileJava {
    options.incremental = true
  }
}

subprojects {
  version = '1.0.0'
  ext.appName = 'topology-visual'
  repositories {
    mavenCentral()
  }
}

eclipse.project.name = 'topology-visual' + '-parent'
