package net.sr89.topology;

import static net.sr89.topology.ExplanationText.ball;

/**
 * What each world is about, in text for {@link ExplanationText}: colors are the ones used in the worlds, and a dot of a
 * color stands for a ball of that color. {@code [[} is a {@code [}.
 */
final class WorldExplanations {
    private static final String GREEN_SURFACE = "#A5B68D";
    private static final String BLUE_HELIX = "#7FA3D6";

    private WorldExplanations() {}

    static final String S1_WITH_COVERING_SPACE = paragraphs(
        "The circle S1 ([" + GREEN_SURFACE + "]green[]) and its universal covering space, the [" + BLUE_HELIX + "]helix[] "
            + "(a copy of the real line, wound around the circle). The fundamental group of S1 is Z.",
        "The covering map drops each point of the helix straight down onto the circle.",
        "Three points of the circle: " + ball("ORANGE") + " " + ball("RED") + " " + ball("MAGENTA") + ". Above each one, "
            + "in the same color, are the points of the helix that fall on it (its preimages): one for each time the "
            + "helix goes around.",
        "Going once around the circle lifts to a path that goes up from one sheet of the helix to the next. This is why "
            + "the fundamental group of the circle is Z.");

    static final String TORUS = paragraphs(
        "The torus T^2 = S1 x S1. Its fundamental group is Z x Z: a loop is determined, up to homotopy, by how many times "
            + "it goes around each way.",
        "[RED]Red[]: the loop a, the long way around. [CYAN]Cyan[]: the loop b, the short way around.",
        "The [" + GREEN_SURFACE + "]green[] loop goes twice the long way and three times the short way: a^2 b^3. "
            + ball("YELLOW") + " moves along it.",
        "Since a b = b a, the group is abelian.");

    static final String GENUS_TWO = paragraphs(
        "The surface of a double torus (genus 2). Its fundamental group is generated by four loops, two for each hole: "
            + "[RED]a1[] and [CYAN]b1[] for the first, [ORANGE]a2[] and [MAGENTA]b2[] for the second. A loop a goes "
            + "around a hole, a loop b goes around the tube of the surface.",
        "There is one relation: [[a1,b1] [[a2,b2] = 1, where [[a,b] = a b a^-1 b^-1. The group is not abelian: "
            + "it is not Z^4.",
        "The [" + GREEN_SURFACE + "]green[] path goes around the first hole while winding once around the tube, then does "
            + "the same around the second hole: roughly a1 b1 a2 b2. " + ball("YELLOW") + " moves along it.");

    static final String UNIVERSAL_COVER_OF_TORUS = paragraphs(
        "The plane R^2 is the universal cover of the torus T^2 = R^2 / Z^2. The covering map wraps the plane around the "
            + "torus: the point (u, v) goes u turns the long way, and v turns the short way.",
        ball("ORANGE") + " The preimages of one point of the torus: there is one in each unit square of the plane. "
            + "The [ORANGE]orange square[] is one of those squares.",
        "The [CYAN]cyan[] path is a straight line in the plane, from (0, 0) to (2, 3). Its image on the torus is the loop "
            + "a^2 b^3, and the path is the lift of that loop: it ends at the preimage (2, 3), not where it started. "
            + "Where it ends tells which element of Z x Z the loop is. " + ball("YELLOW") + " moves along both.");

    static final String PATH_LIFTING = paragraphs(
        "A loop on the circle that goes twice around, but turns back for a while on the way. Each loop can be lifted to the "
            + "helix: there is exactly one path on the helix that starts at a chosen point and falls onto the loop at "
            + "every moment. It is the [ORANGE]orange[] path.",
        "It starts at " + ball("GREEN") + " and ends at " + ball("RED") + ", two sheets higher, above the same point of "
            + "the circle: the loop closes up, but its lift doesn't.",
        "The number of sheets (here 2) is the winding number, which is the element of the fundamental group Z that the loop "
            + "is. Turning back on the way does not change it. " + ball("YELLOW") + " moves along the loop and along its "
            + "lift.");

    static final String KLEIN_BOTTLE = paragraphs(
        "The Klein bottle, drawn as the usual 'figure eight'. It passes through itself here; the real one needs four "
            + "dimensions.",
        "Its fundamental group is <a, b | a b a^-1 b>. The surface is a square: u goes around the [RED]red[] loop a, v goes "
            + "around the [CYAN]cyan[] loop b. The sides are glued as for the torus, except that when u comes around, v is "
            + "reversed. So going around a turns b into b^-1: that is the relation.",
        "It is also what makes the surface non-orientable. The flag shows it: " + ball("YELLOW") + " is on the surface, and "
            + ball("WHITE") + " floats over one side of it. After one lap around a, the flag is on the other side. After "
            + "two laps, it is back.");

    static final String PROJECTIVE_PLANE = paragraphs(
        "The real projective plane RP^2, drawn as Boy's surface: it can't be in 3D without passing through itself. Its "
            + "fundamental group is Z/2 = <a | a^2>: going around the loop a twice is the same as not moving.",
        "The surface is a rectangle whose top and bottom sides are squeezed to one point, " + ball("GREEN")
            + ", the lowest point, where every loop starts and ends. The left and right sides are glued with a flip. "
            + "The left side, from pole to pole, is the [RED]red[] loop a.",
        "Going up a and then down the right side makes a loop that goes twice around a, and that bounds the whole "
            + "rectangle. The " + ball("YELLOW") + " beads are the side that moves from the left to the right, sweeping "
            + "over the rectangle: the loop shrinks to nothing, so a^2 = 1. " + ball("ORANGE") + " goes around the loop.",
        ball("WHITE") + " is the triple point, where three sheets of the surface cross.");

    static final String MOBIUS_BAND = paragraphs(
        "The Mobius band: a strip with a half twist. It shrinks onto its core, the [RED]red[] circle, so its fundamental "
            + "group is Z, generated by the loop a once around the core.",
        "Its boundary, [MAGENTA]magenta[], is one circle that goes twice around the band before it closes: in the "
            + "fundamental group it is a^2. So the inclusion of the boundary into the band is multiplication by 2.",
        "The band is non-orientable. The flag shows it: " + ball("YELLOW") + " is on the surface, and " + ball("WHITE")
            + " floats over one side of it. After one lap around the core, the flag is on the other side. After two "
            + "laps, it is back.");

    static final String SQUARE_TORUS = paragraphs(
        "The torus as a square with its opposite sides glued: a b a^-1 b^-1. The square folds up until the two sides of "
            + "each color meet: the [RED]red[] sides (a) become a circle, and so do the [CYAN]cyan[] sides (b).",
        "All four corners end up as the same point, so a and b are loops through it. They are the generators of the "
            + "fundamental group, and the relation is going around the square: a b a^-1 b^-1 = 1, that is, a b = b a. "
            + "So the group is Z x Z.");

    static final String HEXAGON_TORUS = paragraphs(
        "The torus as a hexagon with its opposite sides glued: a different polygon, but the same surface. The sides that "
            + "are glued together have the same color: [RED]red[], [CYAN]cyan[] and [ORANGE]orange[]. The hexagon folds up "
            + "until the two sides of each color meet.",
        "The six corners end up as just two points of the torus, and the three pairs of sides are three paths between "
            + "them. The fundamental group is still Z x Z, as it is for the square: it only depends on the surface.");

    static final String GENUS_TWO_POLYGON = paragraphs(
        "The octagon with its sides glued like a1 b1 a1^-1 b1^-1 a2 b2 a2^-1 b2^-1 is the genus 2 surface. Sides that are "
            + "glued have the same color: [RED]a1[], [CYAN]b1[], [ORANGE]a2[] and [MAGENTA]b2[].",
        "There is no simple formula for how this octagon folds up. The computer cut the genus 2 surface open along four "
            + "loops through one point, and flattened it onto the octagon. Folding it back brings each pair of sides "
            + "together.",
        "All the corners are the same point. The relation is going around the octagon: [[a1,b1] [[a2,b2] = 1.");

    static final String WEDGE_OF_CIRCLES = paragraphs(
        "The wedge of two circles, a figure eight: the loops [RED]a[] and [CYAN]b[] touch at one point. Its fundamental "
            + "group is the free group on a and b. Unlike for the torus, a b a^-1 b^-1 is not trivial.",
        "Above it, its universal cover: a tree where every vertex has four edges (a, a^-1, b, b^-1), each in the color "
            + "of the loop it covers. Its vertices are the elements of the group. " + ball("GREEN") + " is the root, the "
            + "identity.",
        "The [YELLOW]yellow[] path is the lift of the loop a b a^-1 b^-1, which the " + ball("YELLOW") + " balls follow. "
            + "The loop closes up on the figure eight, but its lift ends at " + ball("RED") + ", not at the root: the "
            + "commutator is not the identity.");

    static final String VAN_KAMPEN = paragraphs(
        "Van Kampen's theorem finds the fundamental group of a space from two pieces that cover it. Here the genus 2 "
            + "surface is made of [#6699FF]A[] and [#FFA64D]B[], which overlap in the neck between the two holes. They move "
            + "apart to show it.",
        "Each piece is a torus with a hole. The group of A is free on [RED]a1[] and [WHITE]b1[], and the group of B is free "
            + "on [GREEN]a2[] and [MAGENTA]b2[].",
        "The overlap is a cylinder, with fundamental group Z, generated by the [YELLOW]yellow[] loop e around the neck. It is "
            + "in both pieces. In A it is [[a1,b1], going around the hole. In B it is the same loop the other way "
            + "around: [[a2,b2]^-1. The theorem says to put the two groups together, and identify the two: "
            + "[[a1,b1] = [[a2,b2]^-1, that is, [[a1,b1] [[a2,b2] = 1. " + ball("YELLOW") + " goes around e in A and in B.");

    /** Paragraphs, with an empty line between them. */
    private static String paragraphs(String... paragraphs) {
        return String.join("\n\n", paragraphs);
    }
}
